# Generated by Django 4.0.5 on 2022-07-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='metacritic_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rotten_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='streaming_sources',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmd_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
