# Generated by Django 4.0.5 on 2022-07-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_image_link_remove_movie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='full_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='stream_sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
