# Generated by Django 4.0.5 on 2022-07-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rotten_critic_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_user_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
