# Generated by Django 4.0.5 on 2022-07-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_movie_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='full_title',
        ),
        migrations.RemoveField(
            model_name='media',
            name='rotten_user_rating',
        ),
        migrations.AlterField(
            model_name='media',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
