# Generated by Django 4.0.5 on 2022-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_media_full_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='rotten_critic_score',
            new_name='metacritic_score',
        ),
        migrations.RemoveField(
            model_name='media',
            name='trailer',
        ),
        migrations.AddField(
            model_name='media',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
