# Generated by Django 4.0.5 on 2022-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rename_rotten_critic_score_media_metacritic_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
